### ISSUE TITLE
Getting StorageDepositLimitExhausted when uploading dns contract to https://contracts-ui.substrate.io/instantiate UI

### ISSUE THREAD

**Issue by muddlebee** [paritytech/ink-examples#22]
UI : https://contracts-ui.substrate.io/instantiate
Error : 
> StorageDepositLimitExhausted
> More storage was created than allowed by the storage deposit limit.

Example contract - https://github.com/paritytech/ink-examples/tree/main/dns

![image](https://github.com/paritytech/ink-examples/assets/8139783/87273657-b28c-494b-9dad-30574720d782)

**Comment by muddlebee** [comment]
getting same issue with erc20 token example as well

**Comment by statictype** [comment]
@muddlebee do you have enough funds in your account? this error is also given when the account balance is too low

**Comment by statictype** [comment]
are the funds available on the Contracts on Rococo parachain or on the Rococo relay chain?

**Comment by muddlebee** [comment]
@statictype thank you so much. I think I missed this part. 
It was little confusing in the docs, as it isn't mentioned in the Getting Started section, but much later down below.
https://use.ink/testnet
